- .pylintrc
- README.md
- algorithms/common/abstract/agent.py
- algorithms/fd/ddpg_agent.py
- algorithms/fd/sac_agent.py
- algorithms/fd/td3_agent.py
- run_lunarlander_continuous.py
Squashed commit of the following:
commit 95b8de77637495d3c98550f6bd5d5bd300c390a6
Author: curt <curt.park@medipixel.io>
Date:   Wed Jan 30 20:38:52 2019 +0900
Add sacfd
> Add sacfd and fix fd priority calculation

- algorithms/a2c/agent.py
- algorithms/bc/ddpg_agent.py
- algorithms/common/abstract/agent.py
- algorithms/common/replaybuffer/priortized_replay_buffer_fd.py
- algorithms/ddpg/agent.py
- algorithms/dpg/agent.py
- algorithms/fd/ddpg_agent.py
- algorithms/fd/sac_agent.py
- algorithms/fd/td3_agent.py
- algorithms/per/ddpg_agent.py
- algorithms/per/sac_agent.py
- algorithms/per/td3_agent.py
- algorithms/ppo/agent.py
- algorithms/reinforce/agent.py
- algorithms/sac/agent.py
- algorithms/td3/agent.py
- algorithms/trpo/agent.py
Squashed commit of the following:
commit 0c7bc5140375e212f6c90226d5a8f829eb476da1
Author: khkim <kh.kim@medipixel.io>
Date:   Thu Jan 31 16:43:36 2019 +0900
Test write log method.
commit 7bea11188eb5cb6bc21228a65d8daa180d178463
Author: khkim <kh.kim@medipixel.io>
Date:   Thu Jan 31 15:51:36 2019 +0900
Make write_log method
> Make a method for logging in agent class

- algorithms/common/noise.py
- algorithms/fd/td3_agent.py
- algorithms/per/td3_agent.py
- algorithms/td3/agent.py
- examples/lunarlander_continuous_v2/per-td3.py
- examples/lunarlander_continuous_v2/td3.py
- examples/lunarlander_continuous_v2/td3fd.py
- examples/reacher-v2/td3.py
Squashed commit of the following:
commit 2bfe8b7d53a8fc0d255ad3d9b208609427ba9179
Author: khkim <kh.kim@medipixel.io>
Date:   Wed Feb 13 11:58:12 2019 +0900
Add random action and done terminal in td3
> Modify random action and done check in td3

- algorithms/dqn/networks.py
- examples/pong_no_frameskip_v4/dqn.py
@Curt-Park late fusion network에 버그 발견해서 고쳤습니다. 확인 부탁드려요.
> Fix bug in late fusion dueling network

- algorithms/common/networks/mlp.py
- algorithms/dqn/agent.py
- algorithms/fd/dqn_agent.py
- examples/lunarlander_v2/dqfd.py
- examples/lunarlander_v2/dqn.py
- examples/pong_no_frameskip_v4/dqn.py
- run_pong_no_frameskip_v4.py
Complete, eventually...
https://app.wandb.ai/curt-park/dqn/runs/h9b5bsu3
> Remove multiprocessing on dqn and tune on pong

- algorithms/dqn/networks.py
- examples/lunarlander_v2/dqn.py
I tuned dqn on lunarlander-v2 again, since we removed multi-processing module usages.
> Tune dqn on lunarlander-v2

- algorithms/common/buffer/priortized_replay_buffer.py
- algorithms/common/networks/cnn.py
- algorithms/common/networks/mlp.py
- algorithms/dqn/networks.py
Issue https://github.com/medipixel/rl_algorithms/issues/123
> Remove late fusion networks

- algorithms/fd/dqn_agent.py
- examples/lunarlander_v2/dqfd.py
- examples/lunarlander_v2/dqn.py
- C51: https://youtu.be/gCTIlJnCyoo
- C51fD: https://youtu.be/ztJZhsPC8PU
- Training progress: https://app.wandb.ai/curt-park/dqn/reports?view=curt-park%2FC51%20%28DQN%2FDQfD%29
> Add demo num in batch for dqfd and tune c51

- algorithms/dqn/utils.py
The test result:
https://app.wandb.ai/curt-park/dqn/reports?view=curt-park%2FPong%20%28DQN%20%2F%20C51%20%2F%20IQN%20%2F%20IQN%20-double%20q%29
> Add double q learning in iqn

- README.md
- algorithms/common/noise.py
- algorithms/td3/agent.py
- examples/lunarlander_continuous_v2/td3.py
- examples/reacher_v2/td3.py
Issue: https://github.com/medipixel/rl_algorithms/issues/129
> Fix td3 performance degradation (#129)

- README.md
Correct hyperlink of class diagram.
> Correct hyperlink of class diagram

- README.md
- algorithms/a2c/agent.py
- algorithms/bc/ddpg_agent.py
- algorithms/bc/sac_agent.py
- algorithms/ddpg/agent.py
- algorithms/dqn/agent.py
- algorithms/fd/ddpg_agent.py
- algorithms/fd/dqn_agent.py
- algorithms/fd/sac_agent.py
- algorithms/per/ddpg_agent.py
- algorithms/ppo/agent.py
- algorithms/sac/agent.py
- algorithms/td3/agent.py
- examples/lunarlander_continuous_v2/a2c.py
- examples/lunarlander_continuous_v2/bc-ddpg.py
- examples/lunarlander_continuous_v2/ddpg.py
- examples/lunarlander_continuous_v2/ddpgfd.py
- examples/lunarlander_continuous_v2/per-ddpg.py
- examples/lunarlander_continuous_v2/ppo.py
- requirements.txt
https://github.com/medipixel/rl_algorithms/issues/68
**owner**: @Curt-Park
- a2c: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/a2c/runs/jmbexhux?workspace=user-curt-park)
- ppo: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/ppo/runs/dk8pcps5?workspace=user-curt-park)
- ddpg: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/ddpg/runs/4ay6x9ee?workspace=user-curt-park), [Reacher-v2](https://app.wandb.ai/khsyee/reinforcement_learning_examples/runs/66tyyf4c)
- per-ddpg: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/ddpg/runs/eg9uljes?workspace=user-curt-park)
- bc-ddpg: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/ddpg/runs/pk6p32fu?workspace=user-curt-park)
- ddpgfd: [LunarLanderContinuous-v2](https://app.wandb.ai/curt-park/ddpg/runs/ …
> Port to pytorch-1.0.1 (#68)

- Makefile
- rl_algorithms/common/buffer/replay_buffer.py
- rl_algorithms/dqn/agent.py
- rl_algorithms/fd/ddpg_agent.py
- rl_algorithms/fd/dqn_agent.py
- rl_algorithms/fd/sac_agent.py
Fix bug: Add batch_size argument n-step buffer
> Add batch_size argument n-step buffer

- configs/lunarlander_v2/dqn.py
- rl_algorithms/common/networks/base_network.py
- rl_algorithms/dqn/agent.py
- rl_algorithms/dqn/utils.py
- tests/test_cnn_cfg.py
fix base_network structure & lunar_lander dqn config to make run_lunar_lander_v2.py work.
> Fix base_network structure & lunar_lander dqn config

- Makefile
- README.md
- configs/pong_no_frameskip_v4/dqn.py
- rl_algorithms/common/abstract/agent.py
- rl_algorithms/common/grad_cam.py
- run_pong_no_frameskip_v4.py
- Add grad cam for agent with convolutional layer
- Update README.md
> Add grad cam for CNN DQN

- configs/reacher_v2/bc_ddpg.py
- configs/reacher_v2/bc_sac.py
- configs/reacher_v2/ddpg.py
- configs/reacher_v2/sac.py
- configs/reacher_v2/td3.py
- rl_algorithms/bc/ddpg_agent.py
- rl_algorithms/bc/sac_agent.py
Fix code to make compatible with her & reacher.
> Fix code to make compatible with her & reacher

- configs/pong_no_frameskip_v4/c51.py
- configs/pong_no_frameskip_v4/dqn.py
- configs/pong_no_frameskip_v4/iqn.py
- configs/pong_no_frameskip_v4/iqn_resnet.py
Fix pong configs grad_cam_layer_lists since registry structure is changed.
> Fix pong configs grad_cam_layer_list 

- rl_algorithms/a2c/agent.py
- rl_algorithms/common/networks/brain.py
- rl_algorithms/ddpg/agent.py
- rl_algorithms/dqn/agent.py
- rl_algorithms/dqn/losses.py
- rl_algorithms/ppo/agent.py
- rl_algorithms/sac/agent.py
- rl_algorithms/td3/agent.py
- tests/test_cnn_cfg.py
> Rename base_network to brain

- .pylintrc
- rl_algorithms/bc/ddpg_agent.py
- rl_algorithms/bc/sac_agent.py
- rl_algorithms/common/abstract/agent.py
- rl_algorithms/common/buffer/priortized_replay_buffer.py
- rl_algorithms/common/buffer/replay_buffer.py
- rl_algorithms/ddpg/agent.py
- rl_algorithms/dqn/agent.py
- rl_algorithms/fd/ddpg_agent.py
- rl_algorithms/fd/dqn_agent.py
- rl_algorithms/fd/sac_agent.py
- rl_algorithms/per/ddpg_agent.py
- rl_algorithms/sac/agent.py
- rl_algorithms/td3/agent.py
> Change buffer sample from tensor to array

- .all-contributorsrc
- README.md
- rl_algorithms/a2c/agent.py
- rl_algorithms/a2c/learner.py
- rl_algorithms/bc/ddpg_agent.py
- rl_algorithms/bc/ddpg_learner.py
- rl_algorithms/bc/sac_agent.py
- rl_algorithms/bc/sac_learner.py
- rl_algorithms/common/abstract/agent.py
- rl_algorithms/common/abstract/learner.py
- rl_algorithms/common/helper_functions.py
- rl_algorithms/ddpg/agent.py
- rl_algorithms/ddpg/learner.py
- rl_algorithms/dqn/agent.py
- rl_algorithms/dqn/learner.py
- rl_algorithms/fd/ddpg_agent.py
- rl_algorithms/fd/ddpg_learner.py
- rl_algorithms/fd/dqn_agent.py
- rl_algorithms/fd/dqn_learner.py
- rl_algorithms/fd/sac_agent.py
- rl_algorithms/fd/sac_learner.py
- rl_algorithms/ppo/agent.py
- rl_algorithms/ppo/learner.py
- rl_algorithms/sac/agent.py
- rl_algorithms/sac/learner.py
- rl_algorithms/td3/agent.py
- rl_algorithms/td3/learner.py
- run_lunarlander_continuous_v2.py
- run_lunarlander_v2.py
Detach all update_model calls to learner class for all agents
> Detach all update_model() method to learner class

- configs/pong_no_frameskip_v4/apex_dqn.py
- rl_algorithms/common/abstract/distributed_logger.py
- rl_algorithms/common/distributed/apex.py
- rl_algorithms/common/distributed/learner.py
- rl_algorithms/common/distributed/worker.py
- rl_algorithms/dqn/worker.py
> Fix Ape-X (inconsistent) memory leak

- rl_algorithms/common/abstract/distributed_logger.py
- rl_algorithms/common/apex/architecture.py
> Fix worker step mismatch error while logging worker scores

- rl_algorithms/common/abstract/distributed_logger.py
- rl_algorithms/common/abstract/distributed_worker.py
- rl_algorithms/common/apex/learner.py
- rl_algorithms/common/apex/worker.py
- rl_algorithms/common/helper_functions.py
- rl_algorithms/dqn/distributed_worker.py
> Fix resnet parameter copy error

- configs/pong_no_frameskip_v4/distillation_dqn.py
- requirements.txt
- rl_algorithms/common/buffer/distillation_buffer.py
- rl_algorithms/distillation/dqn_agent.py
Change loading distillation buffer path
> Change method loading distillation buffer path

- Dockerfile
- Makefile
- configs/pong_no_frameskip_v4/distillation_dqn.py
- pip.conf
- requirements.txt
- rl_algorithms/common/buffer/distillation_buffer.py
- rl_algorithms/distillation/dqn_agent.py
- rl_algorithms/dqn/agent.py
- run_pong_no_frameskip_v4.py
Training teacher agent in Pong environment.
Training student agent using train-phase states betweeun ep0 ~ ep100 gathered by teacher agent above.
avg score of student agent : 16.3
[INFO] test 0 step: 1587 total score: 20
[INFO] test 1 step: 1974 total score: 21
[INFO] test 2 step: 1971 total score: 21
[INFO] test 3 step: 1974 total score: 21
[INFO] test 4 step: 1559 total score: 20
[INFO] test 5 step: 835 total score: -20
[INFO] test 6 step: 1592 total score: 20
[INFO] test 7 step: 1652 total score: 20
[INFO] test 8 step: 1593 total score: 20
[INFO] test 9 step: 1590 total score: 20
Training teacher agent in Pong environment 2.
Training student agent using train-phase last 50,000 states gather by 440ep teacher agent above
avg score of student agent : 20.6
[INFO] test 0 step: 2846 total …
> Add train phase distillation

- README.md
- configs/lunarlander_v2/distillation_dqn.py
- rl_algorithms/common/buffer/distillation_buffer.py
- rl_algorithms/common/helper_functions.py
- rl_algorithms/distillation/README.md
- rl_algorithms/distillation/dqn_agent.py
- run_lunarlander_v2.py
- tests/integration/test_run_agent.py
- tests/integration/test_run_distillation_agent.py
- tests/test_distillation_buffer.py
1. Edit README distillation part
2. add distillation agent & distillation buffer test code
> Add distillation test & Edit distillation README

- configs/lunarlander_v2/distillation_dqn.py
- configs/lunarlander_v2/dqfd.py
- configs/pong_no_frameskip_v4/distillation_dqn.py
- rl_algorithms/common/buffer/distillation_buffer.py
- rl_algorithms/common/helper_functions.py
- rl_algorithms/distillation/README.md
- rl_algorithms/distillation/dqn_agent.py
- tests/integration/test_run_distillation_agent.py
Add new configs "distillation_path_dir" so you can specify the path where the distillation data will be stored.
> Add moddable distillation dir

- rl_algorithms/distillation/dqn_agent.py
Fix creating directory for saving distillation buffer to use same log_cfg.curr_time for directory name.
> Fix distillation time difference & wrong variable name contain_q

- .gitignore
- README.md
- rl_algorithms/common/abstract/agent.py
- rl_algorithms/common/saliency_map.py
- rl_algorithms/recurrent/dqn_agent.py
- run_pong_no_frameskip_v4.py
https://arxiv.org/pdf/1312.6034.pdf
> Add saliency map

- README.md
Add bibtex on readme.
```
@misc{rl_algorithms,
author = {Kim, Kyunghwan and Lee, Chaehyuk and Jeong, Euijin and Han, Jiseong and Kim, Minseop and Yoon, Chris and Kim, Mincheol and Park, Jinwoo},
title = {Medipixel RL algorithms},
year = {2020},
publisher = {Github},
journal = {GitHub repository},
howpublished = {\url{https://github.com/medipixel/rl_algorithms}},
}
```
> Add bibtex on readme

- README.md
Add citation and graph for ACER. #319
> Add ACER on README.md

- rl_algorithms/common/abstract/distributed_logger.py
- rl_algorithms/common/abstract/learner.py
Save config.py to config.yaml due to use yaml config.
> Fix save config.py to config.yaml
